In [1]:
import numpy as np

In [2]:
# dir(np)
# help(np.gcd)
# shift tab - 查看方法参数

1. 从 list 引出 numpy 数组
2. 创建数组 api
3. 查看数组
4. 保存和加载数组
5. 数据类型与转换
6. 数组运算
7. 数组拷贝
8. 索引、切片
9. 形状改变
10. 广播机制
11. 通用函数
12. 矩阵运算

## 引出 numpy 数组

**回顾 list**

In [3]:
lst = [0, 1, 2, 3, 4]

In [4]:
print(lst[0], lst[3], lst[-1])
print(lst[1:3]) # 切片，左开右闭
# 无法一次取出多个

0 3 4
[1, 2]


**根据 list 对象创建 numpy 数组**

In [5]:
arr = np.array(lst)

In [6]:
print(arr[0], arr[3], arr[-1])
print(arr[1:3])

0 3 4
[1 2]


In [7]:
print(arr[[2,4]]) # 一次取出多个

[2 4]


*numpy 数组可以做筛选*

In [8]:
cond = arr < 3

print(cond)
print(arr[cond])

[ True  True  True False False]
[0 1 2]


## 创建数组

In [9]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.zeros(shape = 5)

array([0., 0., 0., 0., 0.])

In [11]:
np.full(shape = 6, fill_value= 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [12]:
np.random.randint(0, 10, size = 10) # (low, high, size), 左开右闭

array([0, 5, 9, 0, 0, 8, 9, 7, 7, 0])

In [13]:
# 正态分布
np.random.randn(3)

array([ 0.22180966, -0.81845897, -2.04815986])

In [14]:
# 等差数列，基本参数为 (start, stop, num)，间隔为 (stop-start)/(num-1)
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
# 关闭科学计数法
np.set_printoptions(suppress=True)
# 等比数列, (start, stop, num)
np.logspace(0, 10, base = 2, num = 11) # [ base^start, ..., base^end ], 一共 num 个元素

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

*二维数组*

In [16]:
np.zeros(shape = (3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 查看数组

In [17]:
arr = np.random.randint(0, 3, size = (2, 3)) + 1
arr

array([[3, 1, 1],
       [3, 2, 1]])

In [18]:
arr.shape

(2, 3)

In [19]:
arr.ndim

2

In [20]:
arr.size

6

In [21]:
# 数据类型
arr.dtype

dtype('int64')

In [22]:
# 每个元素占用的大小，单位为字节
arr.itemsize

8

## 保存和加载数组

**保存多个numpy数组，然后分别加载它们**

In [23]:
arr1 = np.ones(shape = (3, 4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.save('./data1', arr1) # 将 arr1 数组保存到 data1.npy 文件

In [25]:
# 加载 .npy 文件
np.load('./data1.npy')

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**保存多个numpy数组，然后分别加载它们**

In [26]:
arr2 = np.zeros(shape = 4)
arr2

array([0., 0., 0., 0.])

In [27]:
np.savez('./data2', arr1=arr1, arr2=arr2) 
# 使用 savez 方法，第一个参数为文件名，无需指定扩展
#      之后的参数是 数组key = 数组，数组key 可以自定义

In [28]:
np.load('./data2.npz')['arr1']

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.load('./data2.npz')['arr2']

array([0., 0., 0., 0.])

**使用 csv 格式持久化数组**

In [30]:
arr1 = np.random.randint(0, 10, size=10)
arr1

array([8, 0, 5, 5, 0, 4, 9, 9, 5, 6])

In [31]:
#指定后缀为 csv
np.savetxt('./arr.csv', arr1, delimiter=',')

In [32]:
np.loadtxt('./arr.csv', delimiter=',')

array([8., 0., 5., 5., 0., 4., 9., 9., 5., 6.])

## 数据类型与转换

In [33]:
#np.array([1,2,3], dtype=np.uint8)
arr1 = np.array([1,2,3], dtype='uint8')
arr1

array([1, 2, 3], dtype=uint8)

In [34]:
np.arange(-32768, 32769, dtype = np.int16)

array([-32768, -32767, -32766, ...,  32766,  32767, -32768], dtype=int16)

In [35]:
np.arange(-128, 130, dtype = np.int8)

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

**类型转换**

In [36]:
arr2 = np.asarray(arr1, dtype = 'int8')
arr2

array([1, 2, 3], dtype=int8)

In [37]:
arr3 = arr1.astype('int16')
arr3

array([1, 2, 3], dtype=int16)

## 数组运算

In [38]:
nd = np.random.randint(0, 10, size=(3,5))
nd

array([[8, 9, 7, 1, 4],
       [0, 0, 5, 2, 3],
       [0, 6, 6, 7, 7]])

In [39]:
nd + 5

array([[13, 14, 12,  6,  9],
       [ 5,  5, 10,  7,  8],
       [ 5, 11, 11, 12, 12]])

In [40]:
nd - 3

array([[ 5,  6,  4, -2,  1],
       [-3, -3,  2, -1,  0],
       [-3,  3,  3,  4,  4]])

In [41]:
nd * 2

array([[16, 18, 14,  2,  8],
       [ 0,  0, 10,  4,  6],
       [ 0, 12, 12, 14, 14]])

In [42]:
nd / 2

array([[4. , 4.5, 3.5, 0.5, 2. ],
       [0. , 0. , 2.5, 1. , 1.5],
       [0. , 3. , 3. , 3.5, 3.5]])

In [43]:
nd // 2

array([[4, 4, 3, 0, 2],
       [0, 0, 2, 1, 1],
       [0, 3, 3, 3, 3]])

In [44]:
nd % 3

array([[2, 0, 1, 1, 1],
       [0, 0, 2, 2, 0],
       [0, 0, 0, 1, 1]])

In [45]:
nd ** 2

array([[64, 81, 49,  1, 16],
       [ 0,  0, 25,  4,  9],
       [ 0, 36, 36, 49, 49]])

In [46]:
np.power(nd, 2)

array([[64, 81, 49,  1, 16],
       [ 0,  0, 25,  4,  9],
       [ 0, 36, 36, 49, 49]])

In [47]:
nd < 4

array([[False, False, False,  True, False],
       [ True,  True, False,  True,  True],
       [ True, False, False, False, False]])

In [48]:
nd == 4

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

赋值运算

In [49]:
nd = nd + 1
print(nd)
nd = nd - 1

[[ 9 10  8  2  5]
 [ 1  1  6  3  4]
 [ 1  7  7  8  8]]


In [50]:
nd += 1
print(nd)
nd -= 1

[[ 9 10  8  2  5]
 [ 1  1  6  3  4]
 [ 1  7  7  8  8]]


In [51]:
#不支持
#nd /= 3

In [52]:
# 支持
nd //= 3
nd

array([[2, 3, 2, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 2, 2, 2, 2]])

In [53]:
1/nd

/var/folders/bx/3v01n90d57v4nfksc48wtw0w0000gn/T/ipykernel_6007/2935957506.py:1: RuntimeWarning: divide by zero encountered in divide
  1/nd


array([[0.5       , 0.33333333, 0.5       ,        inf, 1.        ],
       [       inf,        inf, 1.        ,        inf, 1.        ],
       [       inf, 0.5       , 0.5       , 0.5       , 0.5       ]])

## 复制

In [54]:
def compare(a, b):
    print('b 和 a 对应同一个内存地址？', b is a)
    print('b 的根数据和 a 一样？', b.base is a)
    print('b 的数据是自己的？', b.flags.owndata)
    print('a 的数据是自己的？', a.flags.owndata)
    b[0,0] = 1024
    display(a, b)

In [55]:
a = np.random.randint(0, 10, size = (4,5))
compare(a, a)

b 和 a 对应同一个内存地址？ True
b 的根数据和 a 一样？ False
b 的数据是自己的？ True
a 的数据是自己的？ True


array([[1024,    4,    8,    9,    3],
       [   1,    4,    2,    9,    5],
       [   6,    4,    5,    0,    3],
       [   6,    8,    4,    2,    9]])

array([[1024,    4,    8,    9,    3],
       [   1,    4,    2,    9,    5],
       [   6,    4,    5,    0,    3],
       [   6,    8,    4,    2,    9]])

In [56]:
a = np.random.randint(0, 10, size = (4,5))
compare(a, a.view())

b 和 a 对应同一个内存地址？ False
b 的根数据和 a 一样？ True
b 的数据是自己的？ False
a 的数据是自己的？ True


array([[1024,    8,    2,    1,    5],
       [   6,    1,    7,    2,    6],
       [   1,    9,    8,    8,    4],
       [   7,    7,    1,    9,    5]])

array([[1024,    8,    2,    1,    5],
       [   6,    1,    7,    2,    6],
       [   1,    9,    8,    8,    4],
       [   7,    7,    1,    9,    5]])

In [57]:
a = np.random.randint(0, 10, size = (4,5))
compare(a, a.copy())

b 和 a 对应同一个内存地址？ False
b 的根数据和 a 一样？ False
b 的数据是自己的？ True
a 的数据是自己的？ True


array([[7, 1, 3, 7, 8],
       [4, 4, 6, 7, 8],
       [6, 2, 4, 4, 4],
       [0, 0, 9, 1, 8]])

array([[1024,    1,    3,    7,    8],
       [   4,    4,    6,    7,    8],
       [   6,    2,    4,    4,    4],
       [   0,    0,    9,    1,    8]])

## 索引、切片和迭代

### 花式索引

In [58]:
arr = np.random.randint(0, 10, 20)
arr

array([4, 3, 4, 4, 8, 1, 1, 0, 1, 9, 5, 7, 1, 1, 8, 4, 4, 3, 1, 1])

In [59]:
# 通过花式索引获取元素，将元素复制到新数组
arr2 = arr[[1,3,5]]
arr2

array([3, 4, 1])

In [60]:
# 修改新数组，不会改变源数组
arr2[0] = -1

In [61]:
arr

array([4, 3, 4, 4, 8, 1, 1, 0, 1, 9, 5, 7, 1, 1, 8, 4, 4, 3, 1, 1])

**二维**

In [62]:
arr3 = np.random.randint(0, 10, size = (4, 5))
arr3

array([[9, 6, 3, 0, 5],
       [7, 8, 2, 4, 8],
       [1, 5, 3, 7, 2],
       [4, 3, 4, 0, 7]])

In [63]:
#取出第 2、4 行
arr3[[1,3]]

array([[7, 8, 2, 4, 8],
       [4, 3, 4, 0, 7]])

In [64]:
#取出 arr3[1,2], arr3[3,4] 两个元素。注意：不是交点处的元素
arr3[[1,3], [2, 4]]

array([2, 7])

In [65]:
# 四个元素，坐标分别为 1,1 3,2 3,3 3,4
arr3[[1, 3, 3, 3], [1, 2, 3, 4]]

#扩展
#arr3[[1, 3, 3, 3], [1]]
# 1,1 3,1 3,1 3,1 四个元素，即 array([3, 6, 6, 6])

array([8, 4, 0, 7])

In [66]:
#取出两行和两列交点处的四个元素
arr3[[1,3]][:, [[3,4]]]

array([[[4, 8]],

       [[0, 7]]])

**元素为布尔类型的花式索引**

In [67]:
arr4 = np.random.randint(0, 100, 20)
arr4

array([53, 44, 76, 67, 76, 50, 84, 87, 62, 70,  0, 87, 78, 83, 36, 74, 84,
       43, 59,  2])

In [68]:
cond = arr4 > 50
cond

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True, False,
        True, False])

In [69]:
arr4[cond]

array([53, 76, 67, 76, 84, 87, 62, 70, 87, 78, 83, 74, 84, 59])

In [70]:
cond1 = arr4 < 20
cond2 = arr4 > 80
cond3 = cond1 | cond2
arr4[cond3]

array([84, 87,  0, 87, 83, 84,  2])

补充：**argsort**

In [71]:
arr5 = np.random.randint(0, 50, size=5)
arr5

array([45,  0,  3, 39, 27])

In [72]:
np.sort(arr5)

array([ 0,  3, 27, 39, 45])

In [73]:
sort_idx = arr5.argsort()
sort_idx

array([1, 2, 4, 3, 0])

In [74]:
arr5[sort_idx]

array([ 0,  3, 27, 39, 45])

### 一维数组

In [75]:
arr1 = np.random.randint(0, 100, size = 10)
arr1

array([66, 25, 56, 42, 93, 47, 18, 47, 55, 43])

In [76]:
arr1[0]

66

In [77]:
arr1[-1]

43

In [78]:
#一次取多个
arr1[[0,2,8]]

array([66, 56, 55])

**切片**

In [79]:
arr1[3:6]

array([42, 93, 47])

In [80]:
#指定步长，arr1[3:6:2] 相当于 arr1[[3,5]]
arr1[3:6:2] == arr1[[3,5]]

array([ True,  True])

In [81]:
#从后向前取，步长为-1
arr1[::-1]

array([43, 55, 47, 18, 47, 93, 42, 56, 25, 66])

### 二维数组

In [82]:
arr2 = np.random.randint(0, 100, size = (3, 5))
arr2

array([[84, 42,  5, 70, 37],
       [83, 74, 51, 34,  8],
       [84, 51, 40, 43, 82]])

In [83]:
arr2[1,1]

74

In [84]:
arr2[-1,-1]

82

In [85]:
#取指定多行
arr2[[0, 2]]

array([[84, 42,  5, 70, 37],
       [84, 51, 40, 43, 82]])

In [86]:
#取指定多列
arr2[:, [0,2,4]]

array([[84,  5, 37],
       [83, 51,  8],
       [84, 40, 82]])

In [87]:
# 第二行
arr2[1]

array([83, 74, 51, 34,  8])

In [88]:
# 第二列
arr2[:, 1]

array([42, 74, 51])

In [89]:
#通过切片取某几行
arr2[1:]

array([[83, 74, 51, 34,  8],
       [84, 51, 40, 43, 82]])

In [90]:
#通过切片取某几列
arr2[:, 3:]

array([[70, 37],
       [34,  8],
       [43, 82]])

In [91]:
# 取第二行后三个数
arr2[1, -3:]
# 等价于
# arr2[1, 2:]
# arr2[1, [2, 3, 4]]
# arr2[1, [-3, -2, -1]]

array([51, 34,  8])

In [92]:
# 使用切片取出右下角 2x2 区域
arr2[-2:, -2:]
# 等价于
# arr2[1:, 3:]
# arr2[[1,2], 3:]
# arr2[1:, [3,4]]

array([[34,  8],
       [43, 82]])

In [93]:
#通过切片指定范围和步长
arr2[:, 1::2]

array([[42, 70],
       [74, 34],
       [51, 43]])

In [94]:
#赋值
arr2[2, [-3, -1]] = 1024
arr2

array([[  84,   42,    5,   70,   37],
       [  83,   74,   51,   34,    8],
       [  84,   51, 1024,   43, 1024]])

## 形状改变

### reshape

In [128]:
arr = np.random.randint(0, 100, size = (3, 4))
arr

array([[44, 70, 32, 11],
       [ 6, 51, 43, 64],
       [12, 13, 53, 64]])

In [130]:
arr.shape

(3, 4)

In [131]:
arr.reshape(4,3)

array([[44, 70, 32],
       [11,  6, 51],
       [43, 64, 12],
       [13, 53, 64]])

In [134]:
arr.reshape(2, 6)

array([[44, 70, 32, 11,  6, 51],
       [43, 64, 12, 13, 53, 64]])

In [135]:
# -1 表示最后自动计算
arr.reshape(2, -1)

array([[44, 70, 32, 11,  6, 51],
       [43, 64, 12, 13, 53, 64]])

In [136]:
arr.reshape(-1, 2)

array([[44, 70],
       [32, 11],
       [ 6, 51],
       [43, 64],
       [12, 13],
       [53, 64]])

In [138]:
# 只指定 -1 会转为一维平铺数组
arr.reshape(-1)

array([44, 70, 32, 11,  6, 51, 43, 64, 12, 13, 53, 64])

### 叠加

In [145]:
arr1 = np.random.randint(0, 10, size=(2, 4))
arr2 = np.random.randint(-5, 5, size=(3, 4))

display(arr1, arr2)

array([[4, 4, 6, 1],
       [8, 5, 7, 7]])

array([[ 0, -2, -2, -4],
       [ 1, -4,  1, -4],
       [ 3,  4, -2, -2]])

In [147]:
# 数组合并，默认进行行合并(axis=0)，需要列数相同，否则报错
np.concatenate([arr1, arr2, arr1])

array([[ 4,  4,  6,  1],
       [ 8,  5,  7,  7],
       [ 0, -2, -2, -4],
       [ 1, -4,  1, -4],
       [ 3,  4, -2, -2],
       [ 4,  4,  6,  1],
       [ 8,  5,  7,  7]])

---

In [148]:
arr1 = np.random.randint(0, 10, size=(3, 5))
arr2 = np.random.randint(-5, 5, size=(3, 4))

display(arr1, arr2)

array([[4, 7, 8, 1, 0],
       [5, 6, 2, 4, 9],
       [3, 0, 7, 9, 7]])

array([[-3,  3,  0, -5],
       [-4,  3, -5, -3],
       [ 2, -1, -2, -3]])

In [153]:
# 指定 axis=1/axis=-1 表示列合并，需要行数相同，否则报错
np.concatenate([arr1, arr2], axis=1)

array([[ 4,  7,  8,  1,  0, -3,  3,  0, -5],
       [ 5,  6,  2,  4,  9, -4,  3, -5, -3],
       [ 3,  0,  7,  9,  7,  2, -1, -2, -3]])

### 拆分

In [170]:
arr1 = np.random.randint(0, 100, size = (6,9))
arr1

array([[83, 75, 41, 24, 65, 13, 28, 87, 83],
       [83, 85, 47, 72, 93,  7, 61, 90, 60],
       [92, 77, 50, 83, 66, 18, 77, 47, 15],
       [97, 92, 57,  9, 76, 46, 58, 30, 35],
       [57, 25, 76,  3, 96, 42,  6, 60, 22],
       [74, 76,  8,  9, 92, 38, 80, 95, 10]])

In [171]:
#按行拆分

#平均拆成两部分
display(np.split(arr1, 2))
print()

#平均拆成三部分
display(np.split(arr1, 3))
print()

#指定拆分点。[1,3,5] -> [:1],[1:3],[3:5],[5:]
display(np.split(arr1, [1,3,5]))

[array([[83, 75, 41, 24, 65, 13, 28, 87, 83],
        [83, 85, 47, 72, 93,  7, 61, 90, 60],
        [92, 77, 50, 83, 66, 18, 77, 47, 15]]),
 array([[97, 92, 57,  9, 76, 46, 58, 30, 35],
        [57, 25, 76,  3, 96, 42,  6, 60, 22],
        [74, 76,  8,  9, 92, 38, 80, 95, 10]])]

[array([[83, 75, 41, 24, 65, 13, 28, 87, 83],
        [83, 85, 47, 72, 93,  7, 61, 90, 60]]),
 array([[92, 77, 50, 83, 66, 18, 77, 47, 15],
        [97, 92, 57,  9, 76, 46, 58, 30, 35]]),
 array([[57, 25, 76,  3, 96, 42,  6, 60, 22],
        [74, 76,  8,  9, 92, 38, 80, 95, 10]])]

[array([[83, 75, 41, 24, 65, 13, 28, 87, 83]]),
 array([[83, 85, 47, 72, 93,  7, 61, 90, 60],
        [92, 77, 50, 83, 66, 18, 77, 47, 15]]),
 array([[97, 92, 57,  9, 76, 46, 58, 30, 35],
        [57, 25, 76,  3, 96, 42,  6, 60, 22]]),
 array([[74, 76,  8,  9, 92, 38, 80, 95, 10]])]

In [172]:
# 同理，按列拆分，需指定轴为 1

display(np.split(arr1, 3, axis=1))

[array([[83, 75, 41],
        [83, 85, 47],
        [92, 77, 50],
        [97, 92, 57],
        [57, 25, 76],
        [74, 76,  8]]),
 array([[24, 65, 13],
        [72, 93,  7],
        [83, 66, 18],
        [ 9, 76, 46],
        [ 3, 96, 42],
        [ 9, 92, 38]]),
 array([[28, 87, 83],
        [61, 90, 60],
        [77, 47, 15],
        [58, 30, 35],
        [ 6, 60, 22],
        [80, 95, 10]])]

### 转置

In [173]:
arr = np.random.randint(0, 10, size=(3,5))
arr

array([[3, 8, 4, 3, 1],
       [4, 1, 8, 1, 7],
       [0, 8, 2, 2, 8]])

In [174]:
arr.reshape(5,3)

array([[3, 8, 4],
       [3, 1, 4],
       [1, 8, 1],
       [7, 0, 8],
       [2, 2, 8]])

In [178]:
# 转置（行变列、列变行）
arr.T

array([[3, 4, 0],
       [8, 1, 8],
       [4, 8, 2],
       [3, 1, 2],
       [1, 7, 8]])

In [181]:
np.transpose(arr)

array([[3, 4, 0],
       [8, 1, 8],
       [4, 8, 2],
       [3, 1, 2],
       [1, 7, 8]])

## 广播

**示例 1**

In [183]:
arr1 = np.random.randint(0, 10, size = (5,3))

arr2 = np.arange(1, 4) # 创建数组 [1,2,3]

display(arr1, arr2)

array([[9, 6, 4],
       [5, 0, 3],
       [6, 8, 9],
       [0, 5, 4],
       [7, 7, 0]])

array([1, 2, 3])

In [184]:
# arr2(1, 4) ===> arr2(5, 4)
arr1 + arr2

array([[10,  8,  7],
       [ 6,  2,  6],
       [ 7, 10, 12],
       [ 1,  7,  7],
       [ 8,  9,  3]])

**示例 2**

In [192]:
arr1 = np.random.randint(0, 10, size = (4, 5))
display(arr1)

# 计算每一列的和
arr2 = arr1.sum(axis = 0)
display(arr2)

# 计算每一项占当前列的百分比
display(arr1 / arr2)

array([[8, 6, 0, 5, 7],
       [7, 8, 2, 0, 7],
       [9, 3, 4, 4, 0],
       [2, 3, 7, 3, 3]])

array([26, 20, 13, 12, 17])

array([[0.30769231, 0.3       , 0.        , 0.41666667, 0.41176471],
       [0.26923077, 0.4       , 0.15384615, 0.        , 0.41176471],
       [0.34615385, 0.15      , 0.30769231, 0.33333333, 0.        ],
       [0.07692308, 0.15      , 0.53846154, 0.25      , 0.17647059]])

## 通用函数

### 一般函数

In [242]:
np.pi

3.141592653589793

In [199]:
np.sin(np.pi / 2)

1.0

In [200]:
np.cos(0)

1.0

---

In [202]:
np.sqrt(1024)

32.0

In [204]:
np.square(32)

1024

In [205]:
np.power(3, 3)

27

In [206]:
2 ** 3

8

In [212]:
8 ** (1/3)

2.0

In [213]:
np.log10(100)

2.0

---

In [221]:
np.ceil(3.99)

4.0

In [223]:
np.floor(3.99)

3.0

In [226]:
np.round(3.10)

3.0

In [235]:
np.round(3.45, decimals=1)

3.4

---

In [218]:
x = np.array([1,2,3,4,5])
y = np.array([5,4,3,2,1])

# 每一列的最大值
np.maximum(x, y)

array([5, 4, 3, 4, 5])

In [219]:
np.minimum(x, y)

array([1, 2, 3, 2, 1])

---

In [220]:
z = np.array([[3,4], [5,6]])
i = np.array([1,2])

# 计算一维数组向量内积
#  11 = 3*1 + 4*2
#  17 = 5*1 + 6*2
np.inner(i, z)

array([11, 17])

---

In [240]:
arr = np.random.randint(0, 50, size = 20)
arr

array([21, 34,  0, 10,  8, 42, 43, 39, 49,  9, 46, 41,  0, 46,  9, 21, 25,
       33, 28, 45])

In [241]:
#指定数组元素范围
np.clip(arr, 10, 40)

array([21, 34, 10, 10, 10, 40, 40, 39, 40, 10, 40, 40, 10, 40, 10, 21, 25,
       33, 28, 40])

### where

In [248]:
a1 = np.random.randint(0, 10, size=10)
a2 = np.random.randint(0, 10, size=10)

display(a1, a2)

cond = np.array([True, False, True, False, True, False, True, False, True, False])

# 根据 cond 进行选择，如果 cond[i] 为真则选择 a1[i]，反之选择 a2[i]
np.where(cond, a1, a2)

array([0, 4, 1, 3, 9, 9, 1, 5, 5, 8])

array([3, 6, 1, 8, 7, 8, 2, 7, 6, 9])

array([0, 6, 1, 8, 9, 8, 1, 7, 5, 9])

In [260]:
a3 = np.random.randint(-5, 105, size=10)
display(a3)

# 如果 a3[i] < 5 则选择 a3[i] 反之 >=5 选择 5
a4 = np.where(0 <= a3, a3, 0)
a5 = np.where(a4 <= 100, a4, 100)
a5

array([ 18,  26,  25,  11,  70,   8,  49,  90,  -2, 102])

array([ 18,  26,  25,  11,  70,   8,  49,  90,   0, 100])

### 集合运算

In [263]:
A = np.array([2, 4, 6, 8])
B = np.array([3, 4, 7, 8])

In [265]:
# 交集
np.intersect1d(A, B)

array([4, 8])

In [266]:
# 并集
np.union1d(A, B)

array([2, 3, 4, 6, 7, 8])

In [269]:
# 差集 A-B：A中有的、B中没有的
np.setdiff1d(A, B)

array([2, 6])

### 数学和统计函数

- min 最小值
- max 最大值
- mean 平均值
- median 中位数
- sum 求和
- std 标准差
- var 方差
- cumsum 累加和
- cumprod
- argmin 最小值索引
- argmax 最大值索引
- argwhere 符合条件元素的索引
- cov 协方差矩阵
- corrcoef 相关性系数


In [270]:
a1 = np.array([1, 7, 2, 19, 23, 0, 88, 11, 6, 11])

a1.min()

0

In [271]:
a1.argmax()

6

In [272]:
np.argwhere(a1 > 10)

array([[3],
       [4],
       [6],
       [7],
       [9]])

In [275]:
# c(i) =  a1[i] + c(i-1)
np.cumsum(a1)

array([  1,   8,  10,  29,  52,  52, 140, 151, 157, 168])

In [277]:
a2 = np.random.randint(0, 10, size=(4,5))
a2

array([[6, 1, 6, 4, 4],
       [7, 5, 6, 8, 2],
       [5, 1, 7, 2, 7],
       [0, 7, 5, 7, 4]])

In [278]:
a2.mean(axis = 0)

array([4.5 , 3.5 , 6.  , 5.25, 4.25])

In [279]:
a2.mean(axis = 1)

array([4.2, 5.6, 4.4, 4.6])

In [281]:
# 协方差矩阵
np.cov(a2, rowvar=True)

array([[ 4.2 ,  1.35,  4.15, -3.9 ],
       [ 1.35,  5.3 , -2.8 ,  0.05],
       [ 4.15, -2.8 ,  7.8 , -4.3 ],
       [-3.9 ,  0.05, -4.3 ,  8.3 ]])

In [282]:
# 相关性系数
np.corrcoef(a2, rowvar=True)

array([[ 1.        ,  0.28613513,  0.72506368, -0.66054273],
       [ 0.28613513,  1.        , -0.43548459,  0.00753864],
       [ 0.72506368, -0.43548459,  1.        , -0.53441927],
       [-0.66054273,  0.00753864, -0.53441927,  1.        ]])

## 矩阵运算

### 矩阵乘法

也称为点乘

In [285]:
A = np.array([[4,2,3],
              [1,3,1]]) # 2x3
B = np.array([[2,7],
              [-5,-7],
              [9,3]])   # 3x2

# A 的最后一维要和 B 的第一维相同
np.dot(A, B)

array([[ 25,  23],
       [ -4, -11]])

In [286]:
A @ B

array([[ 25,  23],
       [ -4, -11]])

In [287]:
A.dot(B)

array([[ 25,  23],
       [ -4, -11]])

### 其他运算

矩阵的逆、行列式、特征值、特征向量、qr分解值、svd分解值


In [298]:
from numpy.linalg import inv, det
A = np.random.randint(1, 10, size=(3,3))
A

array([[3, 1, 1],
       [5, 2, 6],
       [8, 3, 1]])

In [299]:
np.set_printoptions(suppress=True)

# 计算 A 的逆矩阵
B = inv(A)
B

array([[ 2.66666667, -0.33333333, -0.66666667],
       [-7.16666667,  0.83333333,  2.16666667],
       [ 0.16666667,  0.16666667, -0.16666667]])

In [300]:
A @ B

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [301]:
# 行列式，https://en.wikipedia.org/wiki/Determinant
det(A)
# 3(2-18)+(48-5)+(15-16)=-48+43-1=-6

-6.0