## Lab

读取 【iris 数据集】（`iris_dataset.csv`） 中的花萼长度（第一列）数据，对其进行排序、去重、求和、累积和、均值、方差、标准差、最大值、最小值。

In [1]:
import numpy as np

In [2]:
data = np.loadtxt('iris_dataset.csv', delimiter=',')
data.shape

(150, 4)

In [3]:
col1 = data[:, 0]

In [4]:
col1

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [5]:
#排序
col1[col1.argsort()]

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [6]:
#去重
np.unique(col1)

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [7]:
#求和
np.sum(col1)

876.5

In [8]:
#累积和
col1.cumsum()

array([  5.1,  10. ,  14.7,  19.3,  24.3,  29.7,  34.3,  39.3,  43.7,
        48.6,  54. ,  58.8,  63.6,  67.9,  73.7,  79.4,  84.8,  89.9,
        95.6, 100.7, 106.1, 111.2, 115.8, 120.9, 125.7, 130.7, 135.7,
       140.9, 146.1, 150.8, 155.6, 161. , 166.2, 171.7, 176.6, 181.6,
       187.1, 192. , 196.4, 201.5, 206.5, 211. , 215.4, 220.4, 225.5,
       230.3, 235.4, 240. , 245.3, 250.3, 257.3, 263.7, 270.6, 276.1,
       282.6, 288.3, 294.6, 299.5, 306.1, 311.3, 316.3, 322.2, 328.2,
       334.3, 339.9, 346.6, 352.2, 358. , 364.2, 369.8, 375.7, 381.8,
       388.1, 394.2, 400.6, 407.2, 414. , 420.7, 426.7, 432.4, 437.9,
       443.4, 449.2, 455.2, 460.6, 466.6, 473.3, 479.6, 485.2, 490.7,
       496.2, 502.3, 508.1, 513.1, 518.7, 524.4, 530.1, 536.3, 541.4,
       547.1, 553.4, 559.2, 566.3, 572.6, 579.1, 586.7, 591.6, 598.9,
       605.6, 612.8, 619.3, 625.7, 632.5, 638.2, 644. , 650.4, 656.9,
       664.6, 672.3, 678.3, 685.2, 690.8, 698.5, 704.8, 711.5, 718.7,
       724.9, 731. ,

In [9]:
#均值
np.mean(col1)

5.843333333333334

In [10]:
#最大值
col1.max()

7.9

In [11]:
#最小值
col1.min()

4.3

In [12]:
#方差
col1.var()

0.6811222222222223

In [13]:
#标准差
col1.std()

0.8253012917851409