## Practice 2

In [1]:
import numpy as np

### No.1

给定一个 4 维数组，如何得到最后两维所有数据的和？（hint：指定 axis 进行计算）

In [2]:
arr = np.random.randint(0, 20, size = (3, 4, 5, 6))
arr.shape

(3, 4, 5, 6)

In [3]:
# 最后两维求和
res = arr.sum(axis = (-2, -1))
display(res.shape)
display(res)

(3, 4)

array([[290, 291, 265, 280],
       [255, 243, 256, 290],
       [305, 307, 225, 286]])

### No.2

给定数组 `[1,2,3,4,5]`，请在这个数组每个元素之间插入 3 个 0，并打印出新数组

In [4]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [5]:
#17 = 5 + 4*3
arr2 = np.zeros(shape=17, dtype=np.int16)
arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [6]:
arr2[::4] = arr
arr2

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5], dtype=int16)

### No.3

给定一个 2 维矩阵（5x4），如何交换其中两行的元素？（hint：花式索引）

In [7]:
arr = np.random.randint(0, 20, size = (4,5))
arr

array([[15,  0,  8, 10, 15],
       [14,  3, 12,  0, 19],
       [ 2,  6,  4,  7,  0],
       [ 2, 16, 12, 18, 19]])

In [8]:
arr2 = arr[[3, 1, 2, 0]]
arr2

array([[ 2, 16, 12, 18, 19],
       [14,  3, 12,  0, 19],
       [ 2,  6,  4,  7,  0],
       [15,  0,  8, 10, 15]])

### No.4

创建一个长度为 `100000` 的随机数组，使用两种方法对其求三次方（for循环；numpy方法），并统计所用方法

In [9]:
arr = np.random.randint(0, 10, size = 100000)
arr

array([4, 7, 4, ..., 0, 2, 4])

In [10]:
%%time
res1 = np.power(arr, 3)
res1

CPU times: user 2.54 ms, sys: 111 µs, total: 2.65 ms
Wall time: 325 µs


array([ 64, 343,  64, ...,   0,   8,  64])

In [11]:
%%time
res2 = []
for i in arr:
    res2.append(i ** 3)
res2[:4]

CPU times: user 23.6 ms, sys: 995 µs, total: 24.6 ms
Wall time: 9.63 ms


[64, 343, 64, 512]

### No.5

创建一个 5x3 的矩阵和一个 3x2 的矩阵，计算二者乘积

In [12]:
np.random.randint(0, 10, size=(5,3)) @ np.random.randint(0, 10, size=(3,2))

array([[144,  72],
       [146,  74],
       [153,  77],
       [ 59,  31],
       [ 94,  46]])

### No.6

矩阵的每一行的元素都减去改行的平均值（hint：考虑指定 axis）

In [13]:
arr = np.random.randint(0, 10, size = (3,4))
arr

array([[8, 4, 8, 8],
       [8, 4, 1, 1],
       [6, 0, 2, 1]])

In [14]:
line_avg = arr.mean(axis = 1)
line_avg

array([7.  , 3.5 , 2.25])

In [15]:
arr - line_avg.reshape(3, 1)

array([[ 1.  , -3.  ,  1.  ,  1.  ],
       [ 4.5 ,  0.5 , -2.5 , -2.5 ],
       [ 3.75, -2.25, -0.25, -1.25]])

### No.7

创建下边给出矩阵（开始时需要使用 `np.zeros` 创建 8x8 的矩阵）

```
[[0 1 0 1 0 1 0 1] 
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [16]:
arr = np.zeros(shape = (8,8), dtype = np.int16)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [17]:
# 2n 行
arr[::2] = 1
arr[:, ::2] = 0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [18]:
# 2n+1 行
arr[1::2] = 1
arr[1::2, 1::2] = 0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int16)

### No.8

正则化一个 5x5 的随机矩阵（数据从一变成 0~1 之间的数字，相当大进行缩小）

正则化：矩阵 A 中的每一列减去这一列最小值，除以每一列的最大值减去每一列的最小值（hint：指定 axis）

<font size=6>$A = \frac{A - A.min}{A.max - A.min}$</font>

In [19]:
arr = np.random.randint(0, 10, size = (5,5))
arr

array([[8, 7, 8, 0, 2],
       [2, 7, 3, 2, 7],
       [7, 6, 5, 2, 0],
       [0, 2, 4, 0, 9],
       [6, 7, 9, 3, 9]])

In [20]:
col_min = arr.min(axis = 0)
col_max = arr.max(axis = 0)

display(col_min, col_max)

array([0, 2, 3, 0, 0])

array([8, 7, 9, 3, 9])

In [21]:
frac_up = arr - col_min
frac_up

array([[8, 5, 5, 0, 2],
       [2, 5, 0, 2, 7],
       [7, 4, 2, 2, 0],
       [0, 0, 1, 0, 9],
       [6, 5, 6, 3, 9]])

In [22]:
frac_down = col_max - col_min
frac_down

array([8, 5, 6, 3, 9])

In [23]:
frac_up / frac_down

array([[1.        , 1.        , 0.83333333, 0.        , 0.22222222],
       [0.25      , 1.        , 0.        , 0.66666667, 0.77777778],
       [0.875     , 0.8       , 0.33333333, 0.66666667, 0.        ],
       [0.        , 0.        , 0.16666667, 0.        , 1.        ],
       [0.75      , 1.        , 1.        , 1.        , 1.        ]])

### No.9

根据两个或多个调价按过滤 numpy 数组：加载 iris 数据集，筛选出第一列小于 5.0 并且第三列大于 1.5 的数据（使用布尔类型的花式索引进行筛选）

In [24]:
data = np.loadtxt('iris_dataset.csv', delimiter=',')
data.shape

(150, 4)

In [25]:
cond1 = data[:, 0] < 5
cond2 = data[:, 2] > 1.5

cond = cond1 & cond2

In [26]:
data[cond]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

### No.10

计算出 iris 数据集中每个数据在每一行的 sofrmax 得分（hint：exp 表示自然底数 e）

<font size=6>$Softmax(z_i)=\frac{exp(z_i)}{\sum_j{exp(z_j)}}$</font>

In [27]:
np.e ** 2

7.3890560989306495

In [28]:
np.exp(2)

7.38905609893065

In [29]:
data = np.loadtxt('iris_dataset.csv', delimiter=',')
data.shape

(150, 4)

In [30]:
data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [31]:
exp_data = np.exp(data)
exp_data[:3]

array([[164.0219073 ,  33.11545196,   4.05519997,   1.22140276],
       [134.28977968,  20.08553692,   4.05519997,   1.22140276],
       [109.94717245,  24.5325302 ,   3.66929667,   1.22140276]])

In [32]:
row_exp_sum = exp_data.sum(axis = 1)
row_exp_sum.shape

(150,)

In [33]:
res = exp_data / row_exp_sum.reshape(150, 1)
res[:5]

array([[0.81032902, 0.16360261, 0.02003419, 0.00603418],
       [0.84114103, 0.1258083 , 0.02540026, 0.00765041],
       [0.78888466, 0.17602396, 0.02632766, 0.00876372],
       [0.78097135, 0.17425826, 0.03518214, 0.00958825],
       [0.77993968, 0.19233076, 0.02131086, 0.00641871]])