## Practice 1

In [1]:
import numpy as np

### No.1

创建一个长度为 10 的一维全为 0 的 ndarray 数组，然后让第 5 个元素等于 1

In [2]:
arr = np.zeros(shape = 10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### No.2

创建一个元素为从 10 到 49（包含 49）的 ndarray 数组，间隔是 1

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### No.3

将第 2 题中数组的所有元素位置反转

In [5]:
arr = np.arange(10, 50)
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### No.4

使用 np.random.random 创建一个 10*10 的 nparray 数组，并打印出最大和最小元素

In [6]:
arr = np.random.random(size = (10, 10))

In [7]:
arr.max()

0.9900364297050966

In [8]:
arr.min()

0.006689154020528831

### No.5

创建一个 10*10 的 ndarray 数组，矩阵边界为 1，里边全为 0

In [9]:
arr = np.zeros(shape = (10, 10), dtype = np.int16)
arr[0] = 1
arr[9] = 1
arr[:, 0] = 1
arr[:, 9] = 1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

### No.6

创建一个每一行都是从 0 到 4 的 5*5 矩阵

In [10]:
arr = np.zeros(shape = (5,5), dtype = np.int16)

for i in range(1, 5):
    arr[:, i] = arr[:, i-1] + 1

arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int16)

### No.7

- 创建一个范围在 (0,1) 之间的长度为 12 的等差数列
- 创建 `[1,2,4,8,16,32,64,128,256,512,1024]` 的等比数列

In [11]:
np.linspace(0, 1, num = 12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [12]:
np.set_printoptions(suppress=True)
np.logspace(0, 10, num = 11, base = 2)

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

### No.8

创建一个长度为 10 的正态分布数组并排序

In [13]:
arr = np.random.randn(10)
arr

array([-0.13840038,  0.41812934,  0.81694159,  1.01690969,  1.10797941,
       -0.14171018,  0.54807413, -0.05373629,  1.13213248,  0.25924225])

In [14]:
arr[arr.argsort()]

array([-0.14171018, -0.13840038, -0.05373629,  0.25924225,  0.41812934,
        0.54807413,  0.81694159,  1.01690969,  1.10797941,  1.13213248])

### No.9

创建一个长度为 10 的随机数组并将最大值替换为 -100

In [15]:
arr = np.random.randint(0, 10, size = 10)
arr

array([3, 3, 5, 3, 8, 1, 0, 5, 1, 8])

In [16]:
np.where(arr < arr.max(), arr, -100)

array([   3,    3,    5,    3, -100,    1,    0,    5,    1, -100])

### No.10

如何根据第 3 列大小顺序来对一个 5*5 矩阵排序？（提示：查阅 argsort 方法；根据某一列重新组织行顺序）

In [17]:
arr = np.random.randint(0, 10, size=(5,5))
arr

array([[3, 6, 2, 5, 7],
       [5, 5, 8, 1, 6],
       [5, 5, 7, 3, 5],
       [0, 8, 5, 7, 7],
       [7, 1, 4, 6, 5]])

In [18]:
sort_idx = arr[:, 2].argsort()
sort_idx

array([0, 4, 3, 2, 1])

In [19]:
# 按照第三列的大小顺序重新排列所有行
arr[sort_idx]

array([[3, 6, 2, 5, 7],
       [7, 1, 4, 6, 5],
       [0, 8, 5, 7, 7],
       [5, 5, 7, 3, 5],
       [5, 5, 8, 1, 6]])